import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import { AuthProvider } from "@/components/AuthProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WatchOver - Ticket Monitoring",
  description: "Generated by create next app",
  themeColor: "#317EFB", // Controls browser and PWA UI color
  icons: {
    icon: "/icons/logoAlone.svg",               // Browser favicon
    apple: "/icons/icon-192x192.png",           // iOS Add to Home Screen icon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Link to Web App Manifest */}
        <link rel="manifest" href="/manifest.json" />
        {/* Support iOS PWA install */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </head>
      <body
        className={`${inter.variable} ${urbanist.variable} font-body antialiased`}
      >
        <AuthProvider>
          <SideBar>
            {children}
          </SideBar>
        </AuthProvider>
      </body>
    </html>
  );
}
