import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import { AuthProvider } from "@/components/AuthProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WatchOver - Ticket Monitoring",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/logoAlone.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${urbanist.variable} font-body antialiased`}
      >
        <AuthProvider>
          <SideBar>
            {children}
          </SideBar>
        </AuthProvider>
      </body>
    </html>
  );
}
